# Generated by Django 3.1.5 on 2021-02-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_hash',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
