# Generated by Django 3.1.5 on 2021-02-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210203_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advertencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='banido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gratificado',
            field=models.IntegerField(default=0),
        ),
    ]
