# Generated by Django 3.1.5 on 2021-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210204_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_hash',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
