# Generated by Django 3.1.5 on 2021-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210204_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mostrar_perfil',
            field=models.BooleanField(default=True),
        ),
    ]
