# Generated by Django 3.1.5 on 2021-02-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
