# Generated by Django 3.1.5 on 2021-02-03 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_projetos_data_criacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projetos',
            new_name='Projeto',
        ),
    ]
