# Generated by Django 3.1.5 on 2021-02-03 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210203_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='participantes_projeto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pendentes',
            field=models.ManyToManyField(blank=True, related_name='usuarios_pendentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
