# Generated by Django 3.1.5 on 2021-02-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210203_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='url_hash',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
