# Generated by Django 3.1.5 on 2021-02-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210203_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='share_hash',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='url_hash',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
