# Generated by Django 3.1.5 on 2021-02-05 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20210204_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioConvidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizou', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='convidados',
            field=models.ManyToManyField(blank=True, related_name='usuarios_convidados', through='app.UsuarioConvidado', to=settings.AUTH_USER_MODEL),
        ),
    ]
